# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1539a4d18820abd95e9e2823889dbdb7b14b45e12ac36cc92fd474e508b0c96de22d68ffc39710ca9772bd9fc65c60b34ce10427b7a56e5882d6d059accaa0e

test:
  secret_key_base: 9ffa9a25f9bef85ae30cc4f96c8b8e47280b7e5b1c0b04ad4b80024d6ea3a51c5dd7c594287c7dc09ff105c653ef8b15d47f1bb714d76f3a3722550aca43eabf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
